<a href="https://colab.research.google.com/github/MiguelRoiNava/Linear-Algebra-58020/blob/main/Final_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [6]:
import numpy as np
A = np.array([[1, 1, 1],[1, 0, 4],[0, 0, 5]])
print(f'Matrix A:\n {A}')
print()
B = np.array([[89],[89],[95]])
print(f'Matrix A:\n {A}')
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix A:\n{C}')

Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:
[[13.]
 [57.]
 [19.]]


Problem 2

In [12]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #Creates the 3x3 matrix from the system of equations
print(A)#Prints the matrix

B = np.array([[5],[15],[-20]]) #Creates the matrix from the right hand side of the systems
print (B)#Prints the matrix

Apinv = np.linalg.pinv(A) #Computes for the pseudo inverse of A
x = Apinv.dot(B) # apply the pseudo-inverse to the right hand side vector to get the solution

print("\nSolution:")
print(x) #Displays the solution

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]

Solution:
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3

In [1]:
import numpy as np
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A) 
print("The eigenvalue/s is/are:\n",w.round(),"\n")
print("The eigenvector/s is/are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are:
 [-1.  3.  2.] 

The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
