<a href="https://colab.research.google.com/github/MiguelRoiNava/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[2,4,6,8,10],[1,3,5,7,9],[12,14,16,18,20],[11,13,15,17,19],[0,1,2,3,4]])
print(A)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [12 14 16 18 20]
 [11 13 15 17 19]
 [ 0  1  2  3  4]]


In [2]:
import numpy as np 
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(A)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


In [3]:
import numpy as np
A = np.array([[2,3,4,5,6],[3,2,3,4,5],[4,3,2,3,4],[5,4,3,2,3],[6,5,4,3,2]])
print(A)

[[2 3 4 5 6]
 [3 2 3 4 5]
 [4 3 2 3 4]
 [5 4 3 2 3]
 [6 5 4 3 2]]


In [4]:
import numpy as np
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
invC = np.linalg.inv(C) #Inverse of Matrix C
print(invC)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [5]:
import numpy as np
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


In [6]:
import numpy as np 
Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])
Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]])
roots = np.linalg.inv(Equations) @ Constants

print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
